version: '3'
services:
  service:
    image : manojishere/swipe-reload-auth:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    volumes:
        - ./swipe-reload-logs:/logs 